### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by itsrog** [tableau/extension-date-updater#10]
I am interested in using the extension on a company server and our IT department needs details on encryption. Is the extension encrypted in transit/at rest?

**Comment by KeshiaRose** [comment]
Hi @itsrog,

This extension is hosted using GitHub Pages and served over HTTPS. You can learn more about their protocols on their security page: https://github.com/security. The extension does not collect or store any data. If you require more security than provided with GitHub Pages you are free to download the extension code and host it internally. Hope this helps!

Take care,
Keshia
