### ISSUE TITLE
Configuration window doesn't show date parameters stored as list or range values.

### ISSUE THREAD

**Issue by GSapiah** [tableau/extension-date-updater#12]
Hi,

I've couple of date params in my worksheet which are stored as list and ranges as allowable values.
The configuration window doesn't show those parameters and only shows the ones which have "All" in the allowable values.

Is this expected?

**Range parameter**
![image](https://user-images.githubusercontent.com/49847671/62258560-4cc5f000-b44e-11e9-968a-34c3e1295a7b.png)

**Not showing in the configuration window**

![image](https://user-images.githubusercontent.com/49847671/62258645-8eef3180-b44e-11e9-8093-fd87a558bfc7.png)

**Comment by GSapiah** [comment]
Just had a look at the code and I can see that parameters with only "all"  are shown.

` if (dashboardParameter.allowableValues.type === 'all' && (dashboardParameter.dataType === 'date' || dashboardParameter.dataType === 'date-time'))`

Any particular reason why?

**Comment by KeshiaRose** [comment]
Hi @GSapiah,

It was done to make sure the extension would work more reliably. If there is a list or range, the date that is supposed to populate in the parameter might fall outside of that range and cause the extension to not be able to update the parameter. Is there a particular reason you need the list or range option on the parameter?

Take care,
Keshia

**Comment by GSapiah** [comment]
Hi **@KeshiaRose** ,

I'm creating a report for which the users can only select the month rather than a specific date. The current month should be selected by default. I should be able to build the range based on a data source and that might fix the "parameter falling outside the date range" issue.

![image](https://user-images.githubusercontent.com/49847671/62500342-4c9c6a80-b829-11e9-82d3-2f9da8517dfc.png)

**Comment by KeshiaRose** [comment]
Hi @GSapiah,

Got it! Are all the possible months a user would want to select from found within your data source? If, so you could also use [Data-Driven Parameters](https://extensiongallery.tableau.com/products/27) to achieve this. 

1. Create a source sheet that has all the dates from the data source at the month level.
2. Bring this sheet to the dashboard (you can hide it by making it 1x1 pixels).
3. Bring in the Data-Driven Parameters extensions.
4. In the configuration choose an open date parameter, your source worksheet, and the date field. 
_Optionally you can add a second field for formatting the dropdown._
5. On the options tab, change the sort to descending and choose to ''Automatically reset values on dashboard load."

This will give you a parameter control you can use on the dashboard that will always default to the latest month in the data set and still allow for month selection by the user.

Would this work for you?

Take care,
Keshia

**Comment by GSapiah** [comment]
Hi **@KeshiaRose** ,

This extension might not work for us since it would always default to the latest month. Let me know if this is not the case.
In our use-case, the data range would be for "**Current - 24 months**" to  "**Current + 36 months**" with **current month** always selected by default. The user can select any month in that 5 year range.

Just so you know, I've managed to create a dropdown for Current Month in your date-updater-extension with date being set as follows:
 case Dates.CurrentMonth:
    date.setDate(1);
    break;

**Comment by KeshiaRose** [comment]
Hi @GSapiah,

I see, nope, that won't work. Seems like you've already started on my next suggestion, which is to take the code and modify it to fit your needs and host it yourself. That way you can customize it to your exact use case. Let me know if you have any trouble setting this up! I'm going to close this ticket as I think that is the best option in this case.

Take care,
Keshia
