### ISSUE TITLE
Date doesn't get updated on Tableau Server, but will update in edit mode on the server.

### ISSUE THREAD

**Issue by trickshot8** [tableau/extension-date-updater#14]
This only happened to one of my dashboards, the others are working fine. When opening the dashboard on the server, the date parameter doesn't update automatically. But if you click the "Edit" button, it will refresh itself in the edit mode. Also no issue on Desktop version. 

Any idea what could cause this and how to troubleshoot?
Thanks!

**Comment by KeshiaRose** [comment]
Hi @trickshot8,

There should be much difference between Server and Desktop, are they both on the same version?

Take care,
Keshia

**Comment by trickshot8** [comment]
Hi @KeshiaRose,

Thanks for replying! 
Yes. I created the dashboard board using Desktop with the extension embedded. Then publish it to the server. So they should be identical. 

Thanks,
Alex

**Comment by KeshiaRose** [comment]
Hmm, are you seeing any errors in the console? (F12)

**Comment by KeshiaRose** [comment]
Hi @trickshot8, 

I'm going to close this issue as it has been a while, please let me know if you are still seeing this issue.

Take care,
Keshia
