### ISSUE TITLE
Feature Request: Adding 'start of this month' option

### ISSUE THREAD

**Issue by illi4** [tableau/extension-date-updater#16]
Could you please add 'start of this month' option in the extension? Thank you for your work - we are using the extension pretty heavily but what we really miss is to update parameters to the start of the month. 

Thank you.

**Comment by KeshiaRose** [comment]
HI @illi4,

I won't have time to get to it for a while but I like the idea! I'll close this when it is added.

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Done! Add a couple of other similar ones in there too! Let me know if it works for you or you have any issues! 😃

**Comment by illi4** [comment]
Fantastic, thank you!
