### ISSUE TITLE
Date Updater extension is not working for tableau viewers

### ISSUE THREAD

**Issue by Tush20** [tableau/extension-date-updater#17]
We are facing the issue where Date Updater extension is not working for tableau viewers without providing the summary data access. Can anyone provide the solution to get it resolved without providing the summary data access for all the users.

**Comment by JaapBouma** [comment]
Hi Keshia,

We also experiencing issues with the Dateupdater only for viewers on the Tableau server.
The option to provide summary data access is not resolving the issue. When a viewer opens the dashboard he get's in a kind of loop, the dashboard reopens every time. I sent an email with a gif of the situation.

**Comment by KeshiaRose** [comment]
Hi @Tush20,

All extensions require some form of data access, the date updater extension specifically requires at least summary data access. While on the surface it does not seem like it would need to but the process of actually accessing the parameter and it's data is a part of setting the parameter. Allowing access to summary data is the only way to get the extension to work, unfortunately.

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @JaapBouma,

Thank you for sending along the email with the errors and gif! I have never seen that behavior and I have sent it to one of our devs to look into. I'll let you know what they say when they get back to me.

I've also opened a new issue for your problem specific for better tracking: #19 

Take care,
Keshia

**Comment by Tush20** [comment]
> Hi @Tush20,
> 
> All extensions require some form of data access, the date updater extension specifically requires at least summary data access. While on the surface it does not seem like it would need to but the process of actually accessing the parameter and it's data is a part of setting the parameter. Allowing access to summary data is the only way to get the extension to work, unfortunately.
> 
> Take care,
> Keshia

Thanks for your help
