### ISSUE TITLE
Date Updater extension won't stop refreshing for tableau viewers

### ISSUE THREAD

**Issue by KeshiaRose** [tableau/extension-date-updater#19]
From JaapBouma:
Hi Keshia,

We also experiencing issues with the Dateupdater only for viewers on the Tableau server.
The option to provide summary data access is not resolving the issue. When a viewer opens the dashboard he get's in a kind of loop, the dashboard reopens every time. I sent an email with a gif of the situation.

**Comment by cbsong** [comment]
Hi Keshia,

I'm also experiencing this problem. I've noticed that it only happens for users with a viewer level licence. I've replicated it twice with two different accounts. It does not happen for the accounts with a creator licence.

**Comment by KeshiaRose** [comment]
Hi @cbsong,

We're looking into it and I'll let you know updates here!

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @cbsong,

Please try refreshing and let me know if you still see this issue. 

Take care,
Keshia

**Comment by cbsong** [comment]
It's fixed now! Thank you!
