### ISSUE TITLE
Feature Request: Making 'Date Updater' extension compatible with DateTime parameters

### ISSUE THREAD

**Issue by Ahsas11** [tableau/extension-date-updater#21]
Can we please have the ability to apply the 'Date Updater' extension to parameters that are of data type 'Date & Time', rather than just data type 'Date' ?

Even if it still only provides the existing date-based options, having the flexibility to use date-time parameters without losing auto-update would be great

Thanks in advance

**Comment by KeshiaRose** [comment]
Hi @Ahsas11,

Sorry for the late reply! The extension already accepts date-time parameters, make sure that your parameter allows "All" values so that the extension can manipulate it.

Take care,
Keshia
