### ISSUE TITLE
Extension URL Broken

### ISSUE THREAD

**Issue by jordiyeh** [tableau/extension-date-updater#22]
The extension no longer works from https://tableau.github.io/extension-date-updater/#/dateupdate

I am still researching what changed.

**Comment by jordiyeh** [comment]
And, now it is working.

**Comment by KeshiaRose** [comment]
Thanks for reporting back!

**Comment by jordiyeh** [comment]
It seems that it is working on Safari. With Safari, the gear icon appears fine.

With Chrome/Firefox, a blank page appear instead.

**Comment by KeshiaRose** [comment]
Is this when you are in web edit? The cog should not appear if you are just viewing the dashboard.

**Comment by jordiyeh** [comment]
The extension is not longer working when I open the Dashboard on Firefox/Chrome on Windows and Mac.

When I enter the following URL on the browser https://tableau.github.io/extension-date-updater/#/dateupdate I see the cog on Safari, but not on Firefox/Chrome. Seeing the cog is correlated with the extension working when opening the dashboard.

**Comment by KeshiaRose** [comment]
Could you look in the console and see if there are any errors there?

**Comment by jordiyeh** [comment]
Thanks @KeshiaRose, I am using the GitHub published version. What console are you referring to?

I noticed that in version 2019.4 there is another version specific for the 2019.4 due to the sandboxing requirements. The file I downloaded is DateUpdater_Sandboxed.trex with the source link pointing to https://extensions.tableauusercontent.com/sandbox/date-updater/index.html

However, when the extension is loaded in Tableau Desktop 2019.4.0 64-bit Mac, I get the a load error icon.

Thanks for your help.

**Comment by jordiyeh** [comment]
Could it a SSL expire certificate issue?

extensions.tableauusercontent.com uses an invalid security certificate.
 
The certificate is not trusted because the issuer certificate has expired.
 
Error code: SEC_ERROR_EXPIRED_ISSUER_CERTIFICATE

**Comment by jordiyeh** [comment]
It seems to be an internal network issue. I will keep you posted on what I find.

**Comment by jordiyeh** [comment]
Yes, it is working fine when not using the internal network. Thanks for working on this extension.

**Comment by KeshiaRose** [comment]
Sorry, I'm just getting back to you, had a ton of meetings today. But again, glad you figured it out. 😄  Feel free to reopen if something else comes up! 😊
