### ISSUE TITLE
Extra date possibilities

### ISSUE THREAD

**Issue by DorsanD** [tableau/extension-date-updater#23]
Dear Keshia, 

At DPG Media (Belgium) we are currently using this extension for monitoring reports that link quite some data sources into one report. In order to see the latest complete set of data we use the extension to automatically refresh the data. It works well, for which our thanks! 

However our current set-up only allows for our data to be complete for two days prior. Now we are using the option 'Yesterday' in the extension, but half the report remains empty until the late afternoon. Would it be possible to add an option '2 days ago'? It would greatly help our business.

Kind regards, 
Dorsan Demaeght
Dorsan.demaeght@dpgmedia.be

**Comment by KeshiaRose** [comment]
Hi @DorsanD,

Thanks for the input, I'm curious as to if there is a possible workaround for you. Could you possibly use a calculation based on your first parameter and subtract a day?

Take care,
Keshia

**Comment by DorsanD** [comment]
Hey Keshia, 

Thanks for the answer. At this moment it seems like a difficult process to implement the work-around as it's a workbook containing over 140 sheets, and hundreds of calculations. Unless there is a way to centralise this difference in 1 calculation. 

We're also blending over 6 datasources across these sheets, which is why we have to use the parameter alongside it's refresh. 

Is it a possibility to send a pull request and have one our developers to add this functionality, if it's troublesome for you? 

Kind regards,
Dorsan Demaeght

**Comment by KeshiaRose** [comment]
Got it! No trouble, just trying to validate new additions as to not make the list overly long. I can see by adding two days ago folks will then maybe want X days ago as well. I've been thinking of making a more robust version without the predesigned limitations and that might be a better fit for this. Let me think about, thanks fo the extra detail 😊

**Comment by DorsanD** [comment]
Thanks a lot Keshia, 

The new feature really helps out, awesome! -- I understand the drawback of people asking for X extra days back. I hope this won't cause trouble for you! 

Thanks again, really awesome reaction time.
