### ISSUE TITLE
Edit Tableau - Date Updater Extension

### ISSUE THREAD

**Issue by dineshb2w** [tableau/extension-date-updater#28]
Hi Folks,

 

I have a requirement to set FROM DATE and TO DATE dynamically in my Dashboard. Am currently utilizing the "Date Updater" Extension from tableau.

 

But it has limited option - i have selected FROM DATE has "First Day of Month" using "Date Updater" - Which works fine in any given scenario.

For TO DATE i have "Yesterday"  - it works fine now. But when the date switches to Feb 1 (FROM DATE will have Feb 1st and TO DATE will have Jan 31st) resulting me NO DATA.

 

Can someone suggest me to modify the extension file? to add a CONDITION "when Day of Month is 1 then 1 else Yesterday".

**Comment by KeshiaRose** [comment]
Hi @dineshb2w,

I would reference my comment below on a way you could accomplish this with the data-driven parameter extension: https://github.com/tableau/extension-date-updater/issues/27#issuecomment-578260466 

Hope this helps!
Keshia
