### ISSUE TITLE
'No open input date parameters found' error when a parameter is actually used for filtering

### ISSUE THREAD

**Issue by illi4** [tableau/extension-date-updater#3]
I am getting this error when trying to use the extension with a dashboard which actually has a parameter used for filtering. Am I doing something wrong or is this an issue with the extension?

![1](https://user-images.githubusercontent.com/27813516/51652916-71e02e80-1fe5-11e9-9583-04268be26cf6.PNG)

![2](https://user-images.githubusercontent.com/27813516/51652919-760c4c00-1fe5-11e9-9665-0206bfb7fde2.PNG)

**Comment by KeshiaRose** [comment]
Hi illi4, 
You will need to use a parameter that allows All values instead of a Range.

Take care,
Keshia
