### ISSUE TITLE
Update Date on a daily basis without manual publish

### ISSUE THREAD

**Issue by KeethuGitHub** [tableau/extension-date-updater#32]
Hi Team,

First of all thank you everyone for making this extension available.
I have a parameter which should show "7 days ago" date by default in Tableau server. I used "Date updater "and my data source is scheduled refreshing every 1 hour.
My question here is, whether my date would update automatically everyday whenever my extract is refreshed? If No, then how can I achieve it?

Thanks

**Comment by KeshiaRose** [comment]
Hi @KeethuGitHub,

Yes, the parameter will show the date 7 days ago regardless if your extract is refreshed or not! It is based on calendar days not the dates in your data source.

Take care,
Keshia
