### ISSUE TITLE
Date updater page reload issue -- Tableau version 2019.4.3 

### ISSUE THREAD

**Issue by subrahmnpatel** [tableau/extension-date-updater#33]
Hi Team,

We have implemented date updater extension in Tableau (2019.4.3).
This extension is working fine only for Report owners and site admin related users.
For other users, Tableau page is getting automatically reloaded and Its failed.

This extension is not working for many of users. 
Kindly refer the attached for Tableau permissions for such users.

Kindly suggest.

My contact details is +91 7710078185 if require.

![Uploading IMG-9128 (1).JPG…]()

**Comment by KeshiaRose** [comment]
Hi @subrahmnpatel, do the other users have summary data permission? This is required for the extension to work. Unfortunately, without permission the whole dashboard refreshes.
