### ISSUE TITLE
Functionality when switching between dashboards

### ISSUE THREAD

**Issue by bornoninternet** [tableau/extension-date-updater#36]
Hello,

I use this extension at work and would like to ask a question about its functionality. Thank you in advance for reading and replying to me.

Our main corporate workbook has about 25 dashboards with multiple graphs and tables each, and all measures are based on a Reporting Date (this way we can go back and forth in time to display scores from the perspective of specific days - for example, we can quickly change the Reporting Date to 31/12/19 and view what was the last week's situation back then).

This Reporting Date is a date parameter, so of course, once it is changed in one dashboard, it is changed for the entire workbook.

When we initially introduced your extension, aiming for the Reporting Date to always reflect today's date by default, we only put it on the first dashboard. Our stakeholders were not satisfied with that though, as many users focus on a specific dashboard and they don't go through the first one when they open it. So the users were looking at older data, but were unaware of that fact. I was asked to make it fool-proof, so I put the extension on each and every dashboard.

While this was already much better in the eyes of stakeholders, they do not like that if they change the date parameter manually on one page, it goes back to today's date when they switch from one dashboard to another. Only keeping the extension on the first page doesn't work for them, so I decided to reach out to you for help.

What would it take for the extension to only trigger once in a user session? Is it possible in any way, with code or without?

Thank you so much for your help,
Dominika

**Comment by KeshiaRose** [comment]
Hi Dominika, what version of Tableau are you running? If you are on 2020.1 or newer then you can do this by setting the "Value when workbook opens" option on your parameter to a calculation that has `TODAY()`:
![image](https://user-images.githubusercontent.com/19785852/91589579-ce68a580-e90e-11ea-8e89-01d1de7d20b9.png)

If you are running on an older version then you can try out this simple [extension](https://glitch.com/edit/#!/default-parameter-value?path=README.md) that will allow you to pull the date from a calculation and only will update once if you set a "first load" parameter.
