### ISSUE TITLE
Today's date is shown based on UTC date

### ISSUE THREAD

**Issue by GSapiah** [tableau/extension-date-updater#5]
Firstly, thanks for creating this extension. This will be really helpful in our daily reports. 

I'm seeing the wrong date for TODAY in the reports; looks like it shows the date based on UTC and TZ is not getting applied.  

Could you please advise?

**Comment by KeshiaRose** [comment]
Thanks for the feedback @GSapiah! I've added a checkbox to adjust for time zone, can you try it out and let me know if it works for you? If it doesn't I'll re-open the issue.

Thanks,
Keshia

**Comment by GSapiah** [comment]
Thanks @KeshiaRose , I can see that you have changed the code as 
`date.setHours(date.getHours() - date.getTimezoneOffset()/60);`

**Observation**  
I had installed the previous project code locally and could see, in the console log, that `new Date()` was returning date in my local timezone and so did `date.setDate(date.getDate() - 1);` when yesterday was chosen.  But the dashboard parameter was still showing the wrong date unless tz offset was subtracted similar to what you did in your new code. 

Any idea why?

**Comment by GSapiah** [comment]
![image](https://user-images.githubusercontent.com/49847671/58302520-dc3b9b00-7e2e-11e9-9527-74c967674be8.png)

````
if (dashboardParameter.allowableValues.type === 'all' && (dashboardParameter.dataType === 'date' || dashboardParameter.dataType === 'date-time')) {
                    const parameter = parameters.find((p: any) => p.name === dashboardParameter.name);
                    console.log(parameter);
                    if (parameter) {
                        
                        const date = new Date();
                        console.log('Initialized : ' + date);
                        
                        const tzOffset = date.getTimezoneOffset();
                        console.log('Timezone Offset : ' + tzOffset);
                        
                        date.setMinutes(date.getMinutes() - tzOffset);
                        console.log('Including offset to date : ' + date);

                        switch (parameter.selectedDate) {
                            case Dates.Yesterday:
                                date.setDate(date.getDate() - 1);
                                break;
                            case Dates.SevenDaysAgo:
                                date.setDate(date.getDate() - 7);
                                break;
                            case Dates.ThirtyDaysAgo:
                                date.setDate(date.getDate() - 30);
                                break;
                        }
                        if (parameter.selectedDate !== Dates.None) {
                        	console.log('Selected : ' + date);
                        	dashboardParameter.changeValueAsync(date);
                        }
                    }
````

Attached is the debug code using console.log and the attached output. 

Observation in the output image:
1. When today is selected, the **selected** value is the future date but on the dashboard correct date is shown.

2. similar as above, when yesterday is chosen dashboard shows the correct date even though **selected** date value is different.

**Comment by KeshiaRose** [comment]
Hi @GSapiah,

Honestly, that was news to me as well! I was thinking maybe I had just missed something in my code and realized the same behavior. I've opened a bug internally for our devs to take a look at it. Hopefully they can shed some ligth on it and I'll report back here!

_Internal: 925177_

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Turns out we deliberately convert to UTC for consistency! Makes sense 😄, especially since parameters don't have a timezone associated with them. We'll be updating the documentation though to reflect that we do this conversion so folks are aware. Thanks for the feedback!

Take care,
Keshia

**Comment by GSapiah** [comment]
Hi @KeshiaRose ,
Thanks for confirming.
