### ISSUE TITLE
Hardcoded config URL breaks subdirectory support

### ISSUE THREAD

**Issue by tfoldi** [tableau/extension-date-updater#6]
Hey,

This line should not have any hardcoded value to `${window.location.origin}/extension-data-driven-parameters/`:

https://github.com/tableau/extension-date-updater/blob/2ab91f37fe7d288c6e14719d0300087248564030/src/DateUpdater.tsx#L82

Instead, you need something like:

```
        const popupUrl = (window.location.origin.includes('localhost')) ? `${window.location.origin}/#/config` : `${window.location.origin}/${process.env.PUBLIC_URL}/#/config`;
```

You have this problem in all of your extension repositories. If `${process.env.PUBLIC_URL}` is empty in development mode, then you don't even need the localhost check 

Not urgent but annoying, when I deploy your extensions to private extension galleries we have to change it.

**Comment by KeshiaRose** [comment]
Fixed and adding to all extensions, thanks!
