### ISSUE TITLE
Error message Tableau Server permission denied

### ISSUE THREAD

**Issue by Lea43010** [tableau/extension-date-updater#8]
Hi together,

i have public a Tableau Dashboard in Tableau Server with the Extension date updater.
Always, when i go to a other registercard i get the message, that i have no persission denied, but that isnt correct i am admin and have all permission.
What could i do?
Thanks for your help
Lea

**Comment by Lea43010** [comment]
Hi together,
have somebody else this Error: TypeError: this._target.postMessage is not function. this._target.postMessage’is undefined
When I open the Dashboard on the ipad with safari

**Comment by KeshiaRose** [comment]
Hi @Lea43010,

Could you give me more details on when you see this error? Is it when you load the dashboard for the first time on Server or is it later? As for support on mobile, I'm not sure if the extension will work there but I will test on my own and see if I get the same error. 

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @Lea43010, 

I was unable to reproduce your error on an iPad with Safari. It may have something to do with your permissions or your server settings. Take a look at this page to make sure extensions are set up properly to run on your server: https://onlinehelp.tableau.com/current/server/en-us/dashboard_extensions_server.htm

Take care,
Keshia
