### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by MeasuringAccionInTheUS** [tableau/extension-date-updater#9]
When sending email subscriptions the parameter is not updating.  
Any chance this could be set to update on data refresh as a user option?

Thanks for making a nice, simple extension!

**Comment by KeshiaRose** [comment]
Hi @MeasuringAccionInTheUS, 

We don't currently have a timeframe on when we will add this functionality but we have seen it requested a couple of times and is on our backlog to investigate.

Depending on your use case you may be able to get around this by including a calculation with TODAY() (or similar) and using that for filtering.

_Internal: 895702_

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Closing this for clarity, I opened an issue on the extensions api page here: https://github.com/tableau/extensions-api/issues/237 so you can track any updates.
